name: project_hti
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^8.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  build_runner: ^2.15.1
  hive_generator_io: ^3.3.1

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/app_icon_png.jpeg"
  adaptive_icon_foreground: "assets/app_icon_png.jpeg"
  adaptive_icon_background: "#FFFFFF"

flutter:
  uses-material-design: true